// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/addapparel": {
            "post": {
                "description": "Adding new product of category apparel in database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Dashboard"
                ],
                "summary": "Adding new product",
                "parameters": [
                    {
                        "description": "Apparel Data",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ApparelInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Apparel"
                        }
                    }
                }
            }
        },
        "/admin/addcoupon": {
            "post": {
                "description": "Addig coupon for users, with a unique code",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin Dashboard"
                ],
                "summary": "Adding coupon by admin",
                "parameters": [
                    {
                        "description": "coupon",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Coupon"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success masage",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/addoffer": {
            "post": {
                "description": "Addig coupon for users, with a unique code",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin Dashboard"
                ],
                "summary": "Adding offer by admin",
                "parameters": [
                    {
                        "description": "offer",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Offer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success masage",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/deleteapparel/{id}": {
            "delete": {
                "description": "Soft deleting the data of a product from database in category apparel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Dashboard"
                ],
                "summary": "Delete existing product from database",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "product id",
                        "name": "ProductId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Apparel"
                        }
                    }
                }
            }
        },
        "/admin/editapparel/{id}": {
            "put": {
                "description": "Edit data of a product in category apparel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Dashboard"
                ],
                "summary": "Edit existing product data",
                "parameters": [
                    {
                        "description": "Apparel Data",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Apparel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Apparel"
                        }
                    }
                }
            }
        },
        "/admin/home": {
            "get": {
                "description": "Admin dashbord",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "Admin dashbord",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.AdminDashboard"
                        }
                    }
                }
            }
        },
        "/admin/loginpassword": {
            "post": {
                "description": "Admin login with password and phone number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "Admin Login with password",
                "parameters": [
                    {
                        "description": "Admin Data",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Login"
                        }
                    }
                }
            }
        },
        "/admin/registeradmin": {
            "post": {
                "description": "Adding new admin to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "registering new admin",
                "parameters": [
                    {
                        "description": "Admin Data",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Admin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Admin"
                        }
                    }
                }
            }
        },
        "/admin/searchuser": {
            "get": {
                "description": "Showing user list for management by searching with name or id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Dashboard"
                ],
                "summary": "Search user by id or name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User Id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                }
            }
        },
        "/admin/sortuser": {
            "get": {
                "description": "Showing user list for management by sorting with permisiion",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Dashboard"
                ],
                "summary": "User list by permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page no",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "limit no",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "true/false",
                        "name": "permission",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                }
            }
        },
        "/admin/usermanagement": {
            "get": {
                "description": "Showing user list for management by admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Dashboard"
                ],
                "summary": "User list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page no",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "limit no",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                }
            }
        },
        "/admin/userpermission/{id}": {
            "post": {
                "description": "Toggling user permission for block/unblock",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Dashboard"
                ],
                "summary": "block/unblock user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Admin"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Deleting cookie from the browser while logout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "logout",
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/service1/healthcheck": {
            "get": {
                "description": "Service Health Check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "admin\u0026user Authentication service health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/service2/healthcheck": {
            "get": {
                "description": "Service Health Check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Dashboard"
                ],
                "summary": "admin dashboard service health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/loginwithotp": {
            "post": {
                "description": "Login for user with otp",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Phone No",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Login"
                        }
                    }
                }
            }
        },
        "/user/loginwithpassword": {
            "post": {
                "description": "Login for user with password",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Phone No",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Login"
                        }
                    }
                }
            }
        },
        "/user/otpvalidation": {
            "post": {
                "description": "Validating user otp for login validation",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "Otp Validation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Otp",
                        "name": "otp",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Key",
                        "name": "key",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "phone",
                        "name": "phone",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "resend",
                        "name": "resend",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Login"
                        }
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "description": "Adding new user to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "signup",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "userInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Signup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Signup"
                        }
                    }
                }
            }
        },
        "/user/signupotpvalidation": {
            "post": {
                "description": "Validating user otp for signup",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "Sign Up Otp Validation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Twilio Key",
                        "name": "key",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Otp",
                        "name": "otp",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/signupwithotp": {
            "post": {
                "description": "Adding new user to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User\u0026Admin Authentication"
                ],
                "summary": "signup with opt validation",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Signup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Admin": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "adminname": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "entity.AdminDashboard": {
            "type": "object",
            "properties": {
                "averageordervalue": {
                    "type": "integer"
                },
                "newusers": {
                    "type": "integer"
                },
                "pendingorders": {
                    "type": "integer"
                },
                "returnorders": {
                    "type": "integer"
                },
                "stocklesscategory": {
                    "type": "string"
                },
                "totalorders": {
                    "type": "integer"
                },
                "totalproducts": {
                    "type": "integer"
                },
                "totalquery": {
                    "type": "integer"
                },
                "totalrevenue": {
                    "type": "integer"
                },
                "totalusers": {
                    "type": "integer"
                }
            }
        },
        "entity.Apparel": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageurl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "subcategory": {
                    "type": "string"
                }
            }
        },
        "entity.ApparelInput": {
            "type": "object",
            "properties": {
                "apparelid": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageurl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "productCategory": {
                    "type": "string"
                },
                "productId": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "size": {
                    "type": "string"
                },
                "subcategory": {
                    "type": "string"
                }
            }
        },
        "entity.Coupon": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "usage_limit": {
                    "type": "integer"
                },
                "valid_until": {
                    "type": "string"
                }
            }
        },
        "entity.Login": {
            "type": "object",
            "required": [
                "password",
                "phone"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "entity.Offer": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "minprice": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "usage_limit": {
                    "type": "integer"
                },
                "valid_until": {
                    "type": "string"
                }
            }
        },
        "entity.Signup": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "lastname",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "wallet": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	// LeftDelim:        "{{",
	// RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
