definitions:
  entity.Admin:
    properties:
      active:
        type: boolean
      adminname:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      role:
        type: string
    type: object
  entity.AdminDashboard:
    properties:
      averageordervalue:
        type: integer
      newusers:
        type: integer
      pendingorders:
        type: integer
      returnorders:
        type: integer
      stocklesscategory:
        type: string
      totalorders:
        type: integer
      totalproducts:
        type: integer
      totalquery:
        type: integer
      totalrevenue:
        type: integer
      totalusers:
        type: integer
    type: object
  entity.Apparel:
    properties:
      category:
        type: string
      id:
        type: integer
      imageurl:
        type: string
      name:
        type: string
      price:
        type: integer
      subcategory:
        type: string
    type: object
  entity.ApparelInput:
    properties:
      apparelid:
        type: integer
      category:
        type: string
      color:
        type: string
      description:
        type: string
      id:
        type: integer
      imageurl:
        type: string
      name:
        type: string
      price:
        type: integer
      productCategory:
        type: string
      productId:
        type: integer
      quantity:
        type: integer
      size:
        type: string
      subcategory:
        type: string
    type: object
  entity.Coupon:
    properties:
      amount:
        type: integer
      category:
        type: string
      code:
        type: string
      type:
        type: string
      usage_limit:
        type: integer
      valid_until:
        type: string
    type: object
  entity.Login:
    properties:
      password:
        type: string
      phone:
        type: string
    required:
    - password
    - phone
    type: object
  entity.Offer:
    properties:
      amount:
        type: integer
      category:
        type: string
      minprice:
        type: integer
      name:
        type: string
      type:
        type: string
      usage_limit:
        type: integer
      valid_until:
        type: string
    type: object
  entity.Signup:
    properties:
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  entity.User:
    properties:
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      phone:
        type: string
      wallet:
        type: integer
    required:
    - email
    - firstname
    - lastname
    - phone
    type: object
info:
  contact: {}
paths:
  /admin/addapparel:
    post:
      consumes:
      - application/json
      description: Adding new product of category apparel in database
      parameters:
      - description: Apparel Data
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/entity.ApparelInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Apparel'
      summary: Adding new product
      tags:
      - Admin Dashboard
  /admin/addcoupon:
    post:
      consumes:
      - application/json
      description: Addig coupon for users, with a unique code
      parameters:
      - description: coupon
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/entity.Coupon'
      responses:
        "200":
          description: Success masage
          schema:
            type: string
      summary: Adding coupon by admin
      tags:
      - Admin Dashboard
  /admin/addoffer:
    post:
      consumes:
      - application/json
      description: Addig coupon for users, with a unique code
      parameters:
      - description: offer
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/entity.Offer'
      responses:
        "200":
          description: Success masage
          schema:
            type: string
      summary: Adding offer by admin
      tags:
      - Admin Dashboard
  /admin/deleteapparel/{id}:
    delete:
      consumes:
      - application/json
      description: Soft deleting the data of a product from database in category apparel
      parameters:
      - description: product id
        in: query
        name: ProductId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Apparel'
      summary: Delete existing product from database
      tags:
      - Admin Dashboard
  /admin/editapparel/{id}:
    put:
      consumes:
      - application/json
      description: Edit data of a product in category apparel
      parameters:
      - description: Apparel Data
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/entity.Apparel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Apparel'
      summary: Edit existing product data
      tags:
      - Admin Dashboard
  /admin/home:
    get:
      consumes:
      - application/json
      description: Admin dashbord
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.AdminDashboard'
      summary: Admin dashbord
      tags:
      - User&Admin Authentication
  /admin/loginpassword:
    post:
      consumes:
      - application/json
      description: Admin login with password and phone number
      parameters:
      - description: Admin Data
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/entity.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Login'
      summary: Admin Login with password
      tags:
      - User&Admin Authentication
  /admin/registeradmin:
    post:
      consumes:
      - application/json
      description: Adding new admin to the database
      parameters:
      - description: Admin Data
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/entity.Admin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Admin'
      summary: registering new admin
      tags:
      - User&Admin Authentication
  /admin/searchuser:
    get:
      consumes:
      - application/json
      description: Showing user list for management by searching with name or id
      parameters:
      - description: User Name
        in: query
        name: name
        type: string
      - description: User Id
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
      summary: Search user by id or name
      tags:
      - Admin Dashboard
  /admin/sortuser:
    get:
      consumes:
      - application/json
      description: Showing user list for management by sorting with permisiion
      parameters:
      - description: page no
        in: query
        name: page
        type: string
      - description: limit no
        in: query
        name: limit
        type: string
      - description: true/false
        in: query
        name: permission
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
      summary: User list by permission
      tags:
      - Admin Dashboard
  /admin/usermanagement:
    get:
      consumes:
      - application/json
      description: Showing user list for management by admin
      parameters:
      - description: page no
        in: query
        name: page
        type: string
      - description: limit no
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
      summary: User list
      tags:
      - Admin Dashboard
  /admin/userpermission/{id}:
    post:
      consumes:
      - application/json
      description: Toggling user permission for block/unblock
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Admin'
      summary: block/unblock user
      tags:
      - Admin Dashboard
  /logout:
    post:
      consumes:
      - application/json
      description: Deleting cookie from the browser while logout
      produces:
      - application/json
      responses:
        "200":
          description: Success message
          schema:
            type: string
      summary: logout
      tags:
      - User&Admin Authentication
  /service1/healthcheck:
    get:
      consumes:
      - application/json
      description: Service Health Check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: admin&user Authentication service health check
      tags:
      - User&Admin Authentication
  /service2/healthcheck:
    get:
      consumes:
      - application/json
      description: Service Health Check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: admin dashboard service health check
      tags:
      - Admin Dashboard
  /service3/healthcheck:
    get:
      consumes:
      - application/json
      description: Service Health Check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user dashboard service health check
      tags:
      - User Dashboard
  /user/loginwithotp:
    post:
      consumes:
      - multipart/form-data
      description: Login for user with otp
      parameters:
      - description: Phone No
        in: formData
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Login'
      summary: Login
      tags:
      - User&Admin Authentication
  /user/loginwithpassword:
    post:
      consumes:
      - multipart/form-data
      description: Login for user with password
      parameters:
      - description: Phone No
        in: formData
        name: phone
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Login'
      summary: Login
      tags:
      - User&Admin Authentication
  /user/otpvalidation:
    post:
      consumes:
      - multipart/form-data
      description: Validating user otp for login validation
      parameters:
      - description: Otp
        in: formData
        name: otp
        required: true
        type: string
      - description: Key
        in: formData
        name: key
        required: true
        type: string
      - description: phone
        in: formData
        name: phone
        type: string
      - description: resend
        in: formData
        name: resend
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Login'
      summary: Otp Validation
      tags:
      - User&Admin Authentication
  /user/signup:
    post:
      consumes:
      - application/json
      description: Adding new user to the database
      parameters:
      - description: User Data
        in: body
        name: userInput
        required: true
        schema:
          $ref: '#/definitions/entity.Signup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Signup'
      summary: signup
      tags:
      - User&Admin Authentication
  /user/signupotpvalidation:
    post:
      consumes:
      - multipart/form-data
      description: Validating user otp for signup
      parameters:
      - description: Twilio Key
        in: formData
        name: key
        required: true
        type: string
      - description: Otp
        in: formData
        name: otp
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success message
          schema:
            type: string
      summary: Sign Up Otp Validation
      tags:
      - User&Admin Authentication
  /user/signupwithotp:
    post:
      consumes:
      - application/json
      description: Adding new user to the database
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.Signup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
      summary: signup with opt validation
      tags:
      - User&Admin Authentication
swagger: "2.0"
