// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyServiceClient is the client API for MyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyServiceClient interface {
	MyMethod(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	CreateUserWithOtp(ctx context.Context, in *CreateUserWithOtpRequest, opts ...grpc.CallOption) (*CreateUserWithOtpResponse, error)
	SignupOtpValidation(ctx context.Context, in *OtpValidationRequest, opts ...grpc.CallOption) (*OtpValidationResponse, error)
	LoginWithOtp(ctx context.Context, in *LoginWithOtpRequest, opts ...grpc.CallOption) (*LoginWithOtpResponse, error)
	LoginOtpValidation(ctx context.Context, in *OtpValidationRequest, opts ...grpc.CallOption) (*LoginOtpValidationResponse, error)
	LoginWithPassword(ctx context.Context, in *LoginWithPasswordRequest, opts ...grpc.CallOption) (*LoginWithPasswordResponse, error)
	RegisterAdmin(ctx context.Context, in *RegisterAdminRequest, opts ...grpc.CallOption) (*RegisterAdminResponse, error)
	AdminLoginWithPassword(ctx context.Context, in *LoginWithPasswordRequest, opts ...grpc.CallOption) (*LoginWithPasswordResponse, error)
}

type myServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServiceClient(cc grpc.ClientConnInterface) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) MyMethod(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.MyService/MyMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/pb.MyService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) CreateUserWithOtp(ctx context.Context, in *CreateUserWithOtpRequest, opts ...grpc.CallOption) (*CreateUserWithOtpResponse, error) {
	out := new(CreateUserWithOtpResponse)
	err := c.cc.Invoke(ctx, "/pb.MyService/CreateUserWithOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) SignupOtpValidation(ctx context.Context, in *OtpValidationRequest, opts ...grpc.CallOption) (*OtpValidationResponse, error) {
	out := new(OtpValidationResponse)
	err := c.cc.Invoke(ctx, "/pb.MyService/SignupOtpValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) LoginWithOtp(ctx context.Context, in *LoginWithOtpRequest, opts ...grpc.CallOption) (*LoginWithOtpResponse, error) {
	out := new(LoginWithOtpResponse)
	err := c.cc.Invoke(ctx, "/pb.MyService/LoginWithOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) LoginOtpValidation(ctx context.Context, in *OtpValidationRequest, opts ...grpc.CallOption) (*LoginOtpValidationResponse, error) {
	out := new(LoginOtpValidationResponse)
	err := c.cc.Invoke(ctx, "/pb.MyService/LoginOtpValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) LoginWithPassword(ctx context.Context, in *LoginWithPasswordRequest, opts ...grpc.CallOption) (*LoginWithPasswordResponse, error) {
	out := new(LoginWithPasswordResponse)
	err := c.cc.Invoke(ctx, "/pb.MyService/LoginWithPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) RegisterAdmin(ctx context.Context, in *RegisterAdminRequest, opts ...grpc.CallOption) (*RegisterAdminResponse, error) {
	out := new(RegisterAdminResponse)
	err := c.cc.Invoke(ctx, "/pb.MyService/RegisterAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) AdminLoginWithPassword(ctx context.Context, in *LoginWithPasswordRequest, opts ...grpc.CallOption) (*LoginWithPasswordResponse, error) {
	out := new(LoginWithPasswordResponse)
	err := c.cc.Invoke(ctx, "/pb.MyService/AdminLoginWithPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServiceServer is the server API for MyService service.
// All implementations must embed UnimplementedMyServiceServer
// for forward compatibility
type MyServiceServer interface {
	MyMethod(context.Context, *Request) (*Response, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	CreateUserWithOtp(context.Context, *CreateUserWithOtpRequest) (*CreateUserWithOtpResponse, error)
	SignupOtpValidation(context.Context, *OtpValidationRequest) (*OtpValidationResponse, error)
	LoginWithOtp(context.Context, *LoginWithOtpRequest) (*LoginWithOtpResponse, error)
	LoginOtpValidation(context.Context, *OtpValidationRequest) (*LoginOtpValidationResponse, error)
	LoginWithPassword(context.Context, *LoginWithPasswordRequest) (*LoginWithPasswordResponse, error)
	RegisterAdmin(context.Context, *RegisterAdminRequest) (*RegisterAdminResponse, error)
	AdminLoginWithPassword(context.Context, *LoginWithPasswordRequest) (*LoginWithPasswordResponse, error)
	mustEmbedUnimplementedMyServiceServer()
}

// UnimplementedMyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMyServiceServer struct {
}

func (UnimplementedMyServiceServer) MyMethod(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MyMethod not implemented")
}
func (UnimplementedMyServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedMyServiceServer) CreateUserWithOtp(context.Context, *CreateUserWithOtpRequest) (*CreateUserWithOtpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserWithOtp not implemented")
}
func (UnimplementedMyServiceServer) SignupOtpValidation(context.Context, *OtpValidationRequest) (*OtpValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignupOtpValidation not implemented")
}
func (UnimplementedMyServiceServer) LoginWithOtp(context.Context, *LoginWithOtpRequest) (*LoginWithOtpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithOtp not implemented")
}
func (UnimplementedMyServiceServer) LoginOtpValidation(context.Context, *OtpValidationRequest) (*LoginOtpValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginOtpValidation not implemented")
}
func (UnimplementedMyServiceServer) LoginWithPassword(context.Context, *LoginWithPasswordRequest) (*LoginWithPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithPassword not implemented")
}
func (UnimplementedMyServiceServer) RegisterAdmin(context.Context, *RegisterAdminRequest) (*RegisterAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAdmin not implemented")
}
func (UnimplementedMyServiceServer) AdminLoginWithPassword(context.Context, *LoginWithPasswordRequest) (*LoginWithPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminLoginWithPassword not implemented")
}
func (UnimplementedMyServiceServer) mustEmbedUnimplementedMyServiceServer() {}

// UnsafeMyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServiceServer will
// result in compilation errors.
type UnsafeMyServiceServer interface {
	mustEmbedUnimplementedMyServiceServer()
}

func RegisterMyServiceServer(s grpc.ServiceRegistrar, srv MyServiceServer) {
	s.RegisterService(&MyService_ServiceDesc, srv)
}

func _MyService_MyMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).MyMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyService/MyMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).MyMethod(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_CreateUserWithOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserWithOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).CreateUserWithOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyService/CreateUserWithOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).CreateUserWithOtp(ctx, req.(*CreateUserWithOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_SignupOtpValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtpValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).SignupOtpValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyService/SignupOtpValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).SignupOtpValidation(ctx, req.(*OtpValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_LoginWithOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginWithOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).LoginWithOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyService/LoginWithOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).LoginWithOtp(ctx, req.(*LoginWithOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_LoginOtpValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtpValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).LoginOtpValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyService/LoginOtpValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).LoginOtpValidation(ctx, req.(*OtpValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_LoginWithPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginWithPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).LoginWithPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyService/LoginWithPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).LoginWithPassword(ctx, req.(*LoginWithPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_RegisterAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).RegisterAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyService/RegisterAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).RegisterAdmin(ctx, req.(*RegisterAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_AdminLoginWithPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginWithPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).AdminLoginWithPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyService/AdminLoginWithPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).AdminLoginWithPassword(ctx, req.(*LoginWithPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MyService_ServiceDesc is the grpc.ServiceDesc for MyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MyMethod",
			Handler:    _MyService_MyMethod_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _MyService_CreateUser_Handler,
		},
		{
			MethodName: "CreateUserWithOtp",
			Handler:    _MyService_CreateUserWithOtp_Handler,
		},
		{
			MethodName: "SignupOtpValidation",
			Handler:    _MyService_SignupOtpValidation_Handler,
		},
		{
			MethodName: "LoginWithOtp",
			Handler:    _MyService_LoginWithOtp_Handler,
		},
		{
			MethodName: "LoginOtpValidation",
			Handler:    _MyService_LoginOtpValidation_Handler,
		},
		{
			MethodName: "LoginWithPassword",
			Handler:    _MyService_LoginWithPassword_Handler,
		},
		{
			MethodName: "RegisterAdmin",
			Handler:    _MyService_RegisterAdmin_Handler,
		},
		{
			MethodName: "AdminLoginWithPassword",
			Handler:    _MyService_AdminLoginWithPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// AdminDashboardClient is the client API for AdminDashboard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminDashboardClient interface {
	MyMethod(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	SortUserByPermission(ctx context.Context, in *SortUserRequest, opts ...grpc.CallOption) (*SortUserResponse, error)
	SearchUserByname(ctx context.Context, in *SearchUserBynameRequest, opts ...grpc.CallOption) (*SearchUserBynameResponse, error)
	SearchUserByid(ctx context.Context, in *SearchUserByidRequest, opts ...grpc.CallOption) (*SearchUserByidResponse, error)
	TogglePermission(ctx context.Context, in *TogglePermissionRequest, opts ...grpc.CallOption) (*TogglePermissionResponse, error)
	CreateApparel(ctx context.Context, in *CreateApparelRequest, opts ...grpc.CallOption) (*CreateApparelResponse, error)
	EditApparel(ctx context.Context, in *EditApparelResquest, opts ...grpc.CallOption) (*EditApparelResponse, error)
	DeleteApparel(ctx context.Context, in *DeleteApparelRequest, opts ...grpc.CallOption) (*DeleteApparelResponse, error)
	AddCoupon(ctx context.Context, in *AddCouponRequest, opts ...grpc.CallOption) (*AddCouponResponse, error)
	AddOffer(ctx context.Context, in *AddOfferRequest, opts ...grpc.CallOption) (*AddOfferResponse, error)
}

type adminDashboardClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminDashboardClient(cc grpc.ClientConnInterface) AdminDashboardClient {
	return &adminDashboardClient{cc}
}

func (c *adminDashboardClient) MyMethod(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/MyMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDashboardClient) UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/UserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDashboardClient) SortUserByPermission(ctx context.Context, in *SortUserRequest, opts ...grpc.CallOption) (*SortUserResponse, error) {
	out := new(SortUserResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/SortUserByPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDashboardClient) SearchUserByname(ctx context.Context, in *SearchUserBynameRequest, opts ...grpc.CallOption) (*SearchUserBynameResponse, error) {
	out := new(SearchUserBynameResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/SearchUserByname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDashboardClient) SearchUserByid(ctx context.Context, in *SearchUserByidRequest, opts ...grpc.CallOption) (*SearchUserByidResponse, error) {
	out := new(SearchUserByidResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/SearchUserByid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDashboardClient) TogglePermission(ctx context.Context, in *TogglePermissionRequest, opts ...grpc.CallOption) (*TogglePermissionResponse, error) {
	out := new(TogglePermissionResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/TogglePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDashboardClient) CreateApparel(ctx context.Context, in *CreateApparelRequest, opts ...grpc.CallOption) (*CreateApparelResponse, error) {
	out := new(CreateApparelResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/CreateApparel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDashboardClient) EditApparel(ctx context.Context, in *EditApparelResquest, opts ...grpc.CallOption) (*EditApparelResponse, error) {
	out := new(EditApparelResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/EditApparel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDashboardClient) DeleteApparel(ctx context.Context, in *DeleteApparelRequest, opts ...grpc.CallOption) (*DeleteApparelResponse, error) {
	out := new(DeleteApparelResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/DeleteApparel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDashboardClient) AddCoupon(ctx context.Context, in *AddCouponRequest, opts ...grpc.CallOption) (*AddCouponResponse, error) {
	out := new(AddCouponResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/AddCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminDashboardClient) AddOffer(ctx context.Context, in *AddOfferRequest, opts ...grpc.CallOption) (*AddOfferResponse, error) {
	out := new(AddOfferResponse)
	err := c.cc.Invoke(ctx, "/pb.AdminDashboard/AddOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminDashboardServer is the server API for AdminDashboard service.
// All implementations must embed UnimplementedAdminDashboardServer
// for forward compatibility
type AdminDashboardServer interface {
	MyMethod(context.Context, *Request) (*Response, error)
	UserList(context.Context, *UserListRequest) (*UserListResponse, error)
	SortUserByPermission(context.Context, *SortUserRequest) (*SortUserResponse, error)
	SearchUserByname(context.Context, *SearchUserBynameRequest) (*SearchUserBynameResponse, error)
	SearchUserByid(context.Context, *SearchUserByidRequest) (*SearchUserByidResponse, error)
	TogglePermission(context.Context, *TogglePermissionRequest) (*TogglePermissionResponse, error)
	CreateApparel(context.Context, *CreateApparelRequest) (*CreateApparelResponse, error)
	EditApparel(context.Context, *EditApparelResquest) (*EditApparelResponse, error)
	DeleteApparel(context.Context, *DeleteApparelRequest) (*DeleteApparelResponse, error)
	AddCoupon(context.Context, *AddCouponRequest) (*AddCouponResponse, error)
	AddOffer(context.Context, *AddOfferRequest) (*AddOfferResponse, error)
	mustEmbedUnimplementedAdminDashboardServer()
}

// UnimplementedAdminDashboardServer must be embedded to have forward compatible implementations.
type UnimplementedAdminDashboardServer struct {
}

func (UnimplementedAdminDashboardServer) MyMethod(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MyMethod not implemented")
}
func (UnimplementedAdminDashboardServer) UserList(context.Context, *UserListRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (UnimplementedAdminDashboardServer) SortUserByPermission(context.Context, *SortUserRequest) (*SortUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SortUserByPermission not implemented")
}
func (UnimplementedAdminDashboardServer) SearchUserByname(context.Context, *SearchUserBynameRequest) (*SearchUserBynameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserByname not implemented")
}
func (UnimplementedAdminDashboardServer) SearchUserByid(context.Context, *SearchUserByidRequest) (*SearchUserByidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserByid not implemented")
}
func (UnimplementedAdminDashboardServer) TogglePermission(context.Context, *TogglePermissionRequest) (*TogglePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TogglePermission not implemented")
}
func (UnimplementedAdminDashboardServer) CreateApparel(context.Context, *CreateApparelRequest) (*CreateApparelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApparel not implemented")
}
func (UnimplementedAdminDashboardServer) EditApparel(context.Context, *EditApparelResquest) (*EditApparelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditApparel not implemented")
}
func (UnimplementedAdminDashboardServer) DeleteApparel(context.Context, *DeleteApparelRequest) (*DeleteApparelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApparel not implemented")
}
func (UnimplementedAdminDashboardServer) AddCoupon(context.Context, *AddCouponRequest) (*AddCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCoupon not implemented")
}
func (UnimplementedAdminDashboardServer) AddOffer(context.Context, *AddOfferRequest) (*AddOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOffer not implemented")
}
func (UnimplementedAdminDashboardServer) mustEmbedUnimplementedAdminDashboardServer() {}

// UnsafeAdminDashboardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminDashboardServer will
// result in compilation errors.
type UnsafeAdminDashboardServer interface {
	mustEmbedUnimplementedAdminDashboardServer()
}

func RegisterAdminDashboardServer(s grpc.ServiceRegistrar, srv AdminDashboardServer) {
	s.RegisterService(&AdminDashboard_ServiceDesc, srv)
}

func _AdminDashboard_MyMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).MyMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/MyMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).MyMethod(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDashboard_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/UserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).UserList(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDashboard_SortUserByPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).SortUserByPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/SortUserByPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).SortUserByPermission(ctx, req.(*SortUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDashboard_SearchUserByname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserBynameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).SearchUserByname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/SearchUserByname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).SearchUserByname(ctx, req.(*SearchUserBynameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDashboard_SearchUserByid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserByidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).SearchUserByid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/SearchUserByid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).SearchUserByid(ctx, req.(*SearchUserByidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDashboard_TogglePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TogglePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).TogglePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/TogglePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).TogglePermission(ctx, req.(*TogglePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDashboard_CreateApparel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApparelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).CreateApparel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/CreateApparel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).CreateApparel(ctx, req.(*CreateApparelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDashboard_EditApparel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditApparelResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).EditApparel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/EditApparel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).EditApparel(ctx, req.(*EditApparelResquest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDashboard_DeleteApparel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApparelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).DeleteApparel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/DeleteApparel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).DeleteApparel(ctx, req.(*DeleteApparelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDashboard_AddCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).AddCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/AddCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).AddCoupon(ctx, req.(*AddCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminDashboard_AddOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDashboardServer).AddOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdminDashboard/AddOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDashboardServer).AddOffer(ctx, req.(*AddOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminDashboard_ServiceDesc is the grpc.ServiceDesc for AdminDashboard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminDashboard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AdminDashboard",
	HandlerType: (*AdminDashboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MyMethod",
			Handler:    _AdminDashboard_MyMethod_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _AdminDashboard_UserList_Handler,
		},
		{
			MethodName: "SortUserByPermission",
			Handler:    _AdminDashboard_SortUserByPermission_Handler,
		},
		{
			MethodName: "SearchUserByname",
			Handler:    _AdminDashboard_SearchUserByname_Handler,
		},
		{
			MethodName: "SearchUserByid",
			Handler:    _AdminDashboard_SearchUserByid_Handler,
		},
		{
			MethodName: "TogglePermission",
			Handler:    _AdminDashboard_TogglePermission_Handler,
		},
		{
			MethodName: "CreateApparel",
			Handler:    _AdminDashboard_CreateApparel_Handler,
		},
		{
			MethodName: "EditApparel",
			Handler:    _AdminDashboard_EditApparel_Handler,
		},
		{
			MethodName: "DeleteApparel",
			Handler:    _AdminDashboard_DeleteApparel_Handler,
		},
		{
			MethodName: "AddCoupon",
			Handler:    _AdminDashboard_AddCoupon_Handler,
		},
		{
			MethodName: "AddOffer",
			Handler:    _AdminDashboard_AddOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
